import type { Metadata } from "next";
import { FiExternalLink } from "react-icons/fi";
import { FaGithub } from "react-icons/fa";
import { Header } from "../../_components";

export const metadata: Metadata = {
  title: "Saidia — AI-Assisted Logistics Claims | Treva Antony Ogwang",
  description: "How I built a human-centred logistics claims workflow with structured policy checks, grounded AI, PostgreSQL, Make, and Jira.",
  openGraph: { title: "Saidia — AI-Assisted Logistics Claims", description: "A production-minded AI and automation case study by Treva Antony Ogwang.", images: [] },
  twitter: { card: "summary", title: "Saidia — AI-Assisted Logistics Claims", description: "A production-minded AI and automation case study by Treva Antony Ogwang.", images: [] },
};

const liveApp = "https://smartdocassistant-ibk4wvbdysw7fqkfpkxb7q.streamlit.app/";
const github = "https://github.com/Begge10850/smart_doc_assistant";

export default function SaidiaCaseStudy() {
  return <><Header active="Projects"/><main className="case-container saidia-case">
    <section className="case-hero">
      <p className="case-kicker">AI ENGINEERING · AUTOMATION · DATA SYSTEMS · 2026</p>
      <h1>Saidia: preparing logistics claims for reliable human review</h1>
      <p className="case-deck">I built an end-to-end claims assistant for the fictional NorthStar Parcel. It collects complaint-specific facts, applies structured policy rules, explains the assessment in plain language, creates a Jira review ticket, and keeps the final decision with a human.</p>
      <div className="case-actions"><a href={liveApp} target="_blank" rel="noreferrer">Open live application <FiExternalLink/></a><a href={github} target="_blank" rel="noreferrer"><FaGithub/> View source code</a></div>
      <div className="case-facts"><span><b>My role</b>AI &amp; Automation Engineer</span><span><b>Scope</b>Intake to Jira handoff</span><span><b>Core stack</b>Python, PostgreSQL, RAG, Make</span><span><b>Decision owner</b>Human claims reviewer</span></div>
    </section>

    <section className="case-summary"><div><p className="case-kicker">THE SYSTEM AT A GLANCE</p><h2>A claim should arrive ready to review—not buried in disconnected forms, files, and policy text.</h2></div><div><p>Saidia turns a customer report into a structured case. Deterministic rules identify the relevant fictional carrier policy, calculate the deadline, and show which evidence is present or missing. AI makes that assessment easier to understand, while Make and Jira move it into an operational human-review workflow.</p><p className="case-note">Saidia does not approve claims, deny claims, assign liability, or authorise refunds. It prepares the evidence and policy context for the employee who makes the final decision.</p></div></section>

    <section className="case-section"><p className="case-kicker">END-TO-END WORKFLOW</p><h2>From customer report to a review-ready Jira case</h2><div className="saidia-flow">{[['01','Customer intake'],['02','Case & evidence storage'],['03','Policy assessment'],['04','Grounded explanation'],['05','Make orchestration'],['06','Human review in Jira']].map(([n,label]) => <div key={n}><span>{n}</span><b>{label}</b></div>)}</div><p className="saidia-flow-note">Structured rules remain authoritative. The language model explains the result; it does not make the claim decision.</p></section>

    <section className="case-section visual-section"><div className="visual-intro"><p className="case-kicker">CUSTOMER INTAKE</p><h2>One form that adapts to the delivery problem</h2><p className="case-copy">The Streamlit interface changes its questions and evidence guidance for damaged, lost, late, and other delivery problems. A customer can submit an incomplete claim, and the reviewer can immediately see what is still missing.</p></div><figure className="saidia-screen"><img src="/projects/saidia/customer-claim-form.png" alt="Saidia customer claim form with conditional evidence fields"/><figcaption>Complaint-specific fields and evidence guidance</figcaption></figure></section>

    <section className="case-section"><p className="case-kicker">DECISION DESIGN</p><h2>Structured rules first, AI second</h2><div className="principle-grid"><article><b>Deterministic assessment</b><p>Python and PostgreSQL match the case to the appropriate carrier, country, and complaint policy. The system calculates filing deadlines and compares required evidence with what the customer declared.</p></article><article><b>Grounded AI explanation</b><p>Retrieved policy context and verified case facts are passed to the language model for plain-language summaries and case Q&amp;A. The model is not allowed to invent policy or override the structured result.</p></article></div><div className="saidia-gallery two"><figure><img src="/projects/saidia/result-overview.png" alt="Saidia case result with Jira ticket and grounded analysis"/><figcaption>Case result and policy explanation</figcaption></figure><figure><img src="/projects/saidia/assessment-and-qa.png" alt="Saidia claim assessment and grounded question answer"/><figcaption>Evidence gaps, recommendation, and grounded Q&amp;A</figcaption></figure></div></section>

    <section className="case-section"><p className="case-kicker">TECHNOLOGY CHOICES</p><h2>Why this stack</h2><div className="saidia-stack"><article><b>PostgreSQL + Supabase</b><p>Claims need relational integrity, transactions, and database constraints—not only flexible storage. Supabase provided managed PostgreSQL and secure application access.</p></article><article><b>pgvector</b><p>Policy embeddings live beside the relational case data. This avoided a separate vector database while still supporting semantic retrieval with normal PostgreSQL operations.</p></article><article><b>all-mpnet-base-v2</b><p>This sentence-transformer produces 768-dimensional embeddings with strong general semantic retrieval quality—a practical balance of relevance, reproducibility, and cost for a focused policy library.</p></article><article><b>LLM + RAG</b><p>RAG supplies relevant policy passages and verified case facts before generation. The model is used where language helps—explanations and answers—not where deterministic business rules are safer.</p></article><article><b>Private S3 evidence storage</b><p>Original uploads remain private and are shared through time-limited links. Images are stored for human inspection; they are not automatically interpreted.</p></article><article><b>Make + Jira</b><p>Make handles the external workflow and attachments. Jira gives reviewers an existing operational queue rather than requiring another custom employee dashboard.</p></article></div></section>

    <section className="case-section visual-section reverse"><figure className="saidia-screen wide"><img src="/projects/saidia/make-execution.png" alt="Successful Make automation execution for a Saidia claim"/><figcaption>Successful orchestration, attachment transfer, and response</figcaption></figure><div className="visual-intro"><p className="case-kicker">OPERATIONAL HANDOFF</p><h2>Automation connects the product to real review work</h2><p className="case-copy">After a new claim is created, Make opens the Jira issue, downloads the private evidence, attaches each file, records the Jira key, and returns the result to Streamlit. The data-store record is written only after Jira creation, so duplicates can stop before creating another ticket.</p></div></section>

    <section className="case-section"><p className="case-kicker">REVIEW EXPERIENCE</p><h2>The reviewer receives the facts, policy context, gaps, and original evidence together</h2><div className="saidia-gallery two"><figure><img src="/projects/saidia/jira-overview.png" alt="Jira claim ticket with case details and grounded analysis"/><figcaption>Structured case and policy context in Jira</figcaption></figure><figure><img src="/projects/saidia/jira-attachments.png" alt="Jira ticket showing recommendation, human review notice, and attachments"/><figcaption>Actionable recommendation and original attachments</figcaption></figure></div></section>

    <section className="case-section saidia-reliability"><div><p className="case-kicker">PRODUCTION-MINDED RELIABILITY</p><h2>Duplicate protection works across the application, database, and automation</h2><p className="case-copy">Every shipment receives one normalized lookup key. The application checks for an active case, PostgreSQL enforces one active case per shipment under concurrent requests, and Make checks the same key before Jira creation. A repeated report returns the original case reference instead of opening another ticket.</p></div><figure className="saidia-screen"><img src="/projects/saidia/duplicate-reference.png" alt="Saidia duplicate warning returning the existing case reference"/><figcaption>Duplicate stopped before Jira; original reference returned</figcaption></figure></section>

    <section className="case-section saidia-boundaries"><div><p className="case-kicker">WHAT THIS DEMONSTRATES</p><h2>A practical AI system needs boundaries as much as intelligence.</h2></div><div><p>I designed the database model, policy engine, retrieval pipeline, prompts, customer experience, automation handoff, duplicate safeguards, and grounded case Q&amp;A as one coherent workflow.</p><p><b>Current boundaries:</b> NorthStar Parcel and its policies are fictional. The MVP focuses on one carrier workflow. Uploaded images are preserved for human review, not analysed by computer vision. The employee workflow uses Jira rather than a custom internal dashboard.</p></div></section>

    <section className="case-closing"><p className="case-kicker">EXPLORE THE PROJECT</p><h2>See the workflow in action or inspect the implementation.</h2><div className="case-actions"><a href={liveApp} target="_blank" rel="noreferrer">Open live application <FiExternalLink/></a><a href={github} target="_blank" rel="noreferrer"><FaGithub/> View source code</a></div></section>
  </main></>;
}
