import type { Metadata } from "next";
import { FiExternalLink } from "react-icons/fi";
import { FaGithub } from "react-icons/fa";
import { Header } from "../../_components";
import { ZoomableDiagram, ZoomableImage } from "./ZoomableMedia";

export const metadata: Metadata = {
  title: "Saidia: AI-Assisted Logistics Claims | Treva Antony Ogwang",
  description: "How I built a human-centred logistics claims workflow with structured policy checks, grounded AI, PostgreSQL, Make, and Jira.",
  openGraph: { title: "Saidia: AI-Assisted Logistics Claims", description: "A production-minded AI and automation case study by Treva Antony Ogwang.", images: [] },
  twitter: { card: "summary", title: "Saidia: AI-Assisted Logistics Claims", description: "A production-minded AI and automation case study by Treva Antony Ogwang.", images: [] },
};

const liveApp = "https://smartdocassistant-ibk4wvbdysw7fqkfpkxb7q.streamlit.app/";
const github = "https://github.com/Begge10850/smart_doc_assistant";

export default function SaidiaCaseStudy() {
  return <><Header active="Projects"/><main className="case-container saidia-case">
    <section className="case-hero">
      <p className="case-kicker">AI ENGINEERING · AUTOMATION · DATA SYSTEMS · 2026</p>
      <h1>Saidia: preparing logistics claims for reliable human review</h1>
      <p className="case-deck">I built an end-to-end claims assistant for the fictional NorthStar Parcel. It collects complaint-specific facts, applies structured policy rules, explains the assessment in plain language, creates a Jira review ticket, and keeps the final decision with a human.</p>
      <div className="case-actions"><a href={liveApp} target="_blank" rel="noreferrer">Open live application <FiExternalLink/></a><a href={github} target="_blank" rel="noreferrer"><FaGithub/> View source code</a></div>
      <div className="case-facts"><span><b>My role</b>AI &amp; Automation Engineer</span><span><b>Scope</b>Intake to Jira handoff</span><span><b>Core stack</b>Python, PostgreSQL, RAG, Make</span><span><b>Decision owner</b>Human claims reviewer</span></div>
    </section>

    <section className="case-summary"><div><p className="case-kicker">THE SYSTEM AT A GLANCE</p><h2>A claim should arrive ready to review, with its facts, evidence, and policy context connected.</h2></div><div><p>Saidia turns a customer report into a structured case. Deterministic rules select the relevant NorthStar Parcel policy for the complaint type and country, calculate the deadline, and show which evidence is present or missing. AI makes that assessment easier to understand, while Make and Jira move it into an operational human-review workflow.</p><p className="case-note">Saidia does not approve claims, deny claims, assign liability, or authorise refunds. It prepares the evidence and policy context for the employee who makes the final decision.</p></div></section>

    <section className="case-section saidia-diagram-section">
      <div className="saidia-diagram-copy"><p className="case-kicker">SYSTEM ARCHITECTURE</p><h2>Each part of the system has one clear responsibility</h2><p>The Streamlit interface collects the report, while the Python application coordinates storage, policy assessment, retrieval, and the external workflow. PostgreSQL holds the structured case data and policy rules. pgvector adds semantic retrieval without introducing a separate vector database. Make carries the completed case into Jira, where a person reviews it.</p><p>This separation matters because the language model never becomes the source of truth. It receives verified calculations and retrieved policy passages, then turns them into language that is easier to understand.</p></div>
      <figure className="saidia-diagram"><ZoomableDiagram title="End-to-end system architecture"><div className="diagram architecture-diagram"><div className="diagram-lane"><div className="diagram-node actor">Customer</div><span>submits</span><div className="diagram-node interface">Streamlit</div><span>calls</span><div className="diagram-node core">Python application</div></div><div className="diagram-branches"><div><div className="diagram-node data">PostgreSQL + Supabase</div><small>Cases and structured policy rules</small></div><div><div className="diagram-node data">pgvector</div><small>Relevant policy passages</small></div><div><div className="diagram-node storage">Private evidence storage</div><small>Original files for human inspection</small></div></div><div className="diagram-lane"><div className="diagram-node language">LLM explanation</div><span>returns clarity</span><div className="diagram-node automation">Make</div><span>creates</span><div className="diagram-node review">Jira + human reviewer</div></div></div></ZoomableDiagram><figcaption>The application connects deterministic assessment, grounded language, and operational review. Click to enlarge.</figcaption></figure>
    </section>

    <section className="case-section saidia-diagram-section reverse">
      <div className="saidia-diagram-copy"><p className="case-kicker">CLAIM PROCESSING</p><h2>A successful submission follows a controlled sequence</h2><p>The case is validated and stored before the policy engine calculates the deadline and identifies evidence gaps. Only then does the language model explain the verified result. Before Jira is created, Make checks the same tracking identifier used by the application and database.</p><p>A new claim continues to Jira and is recorded with its Jira key. A repeat claim takes the other branch, returns the existing case reference, and stops. This is what prevents a duplicate ticket rather than merely hiding the submit button.</p></div>
      <figure className="saidia-diagram"><ZoomableDiagram title="Claim processing and duplicate prevention"><div className="diagram process-diagram"><div className="process-row">{["Validate input","Create case","Apply policy","Calculate deadline","Check evidence","Explain result"].map((label, index) => <div className="process-step" key={label}><b>{index + 1}</b><span>{label}</span></div>)}</div><div className="decision-line"><span>Make checks tracking identifier</span><b>Existing processed claim?</b></div><div className="decision-branches"><div className="branch duplicate"><strong>Yes</strong><span>Return duplicate message</span><span>Show existing case reference</span><b>Stop before Jira</b></div><div className="branch new"><strong>No</strong><span>Create Jira ticket</span><span>Attach evidence</span><span>Save case and Jira keys</span><b>Return result to Streamlit</b></div></div></div></ZoomableDiagram><figcaption>The duplicate branch ends before Jira; the new-claim branch records the result after Jira creation. Click to enlarge.</figcaption></figure>
    </section>

    <section className="case-section visual-section"><div className="visual-intro"><p className="case-kicker">CUSTOMER INTAKE</p><h2>One form that adapts to the delivery problem</h2><p className="case-copy">A damaged parcel needs different facts from a lost or late parcel. The Streamlit interface therefore changes its questions and evidence guidance after the customer selects the complaint type. Incomplete evidence does not block the report. The case is preserved, and the reviewer can immediately see what is still missing.</p></div><figure className="saidia-screen"><ZoomableImage src="/projects/saidia/customer-claim-form.png" alt="Saidia customer claim form with conditional evidence fields"/><figcaption>Complaint-specific fields and evidence guidance. Click to enlarge.</figcaption></figure></section>

    <section className="case-section saidia-narrative"><p className="case-kicker">DECISION DESIGN</p><h2>Structured rules first, AI second</h2><h3>Deterministic assessment</h3><p>NorthStar Parcel is the only carrier in this fictional system. Python and PostgreSQL select the relevant NorthStar policy using the country and complaint type. The system calculates the filing deadline from the recorded dates and compares the policy requirements with the evidence declared by the customer. The same facts therefore produce the same result every time.</p><h3>Grounded AI explanation</h3><p>The language model receives the verified assessment and retrieved policy context. Its job is to explain why the policy applies and answer the reviewer’s question in normal language. It cannot change a deadline, invent a requirement, or override the structured result.</p><div className="saidia-gallery two"><figure><ZoomableImage src="/projects/saidia/result-overview.png" alt="Saidia case result with Jira ticket and grounded analysis"/><figcaption>Case result and policy explanation. Click to enlarge.</figcaption></figure><figure><ZoomableImage src="/projects/saidia/assessment-and-qa.png" alt="Saidia claim assessment and grounded question answer"/><figcaption>Evidence gaps, recommendation, and grounded case Q&amp;A. Click to enlarge.</figcaption></figure></div></section>

    <section className="case-section saidia-diagram-section">
      <div className="saidia-diagram-copy"><p className="case-kicker">GROUNDED CASE Q&amp;A</p><h2>The answer begins with facts, not with the model</h2><p>When an employee asks a question, the system gathers the saved case facts and the structured policy assessment. It also converts the question into an embedding and uses pgvector to find policy passages with similar meaning, even when the wording differs.</p><p>Those three sources become the model&apos;s context. The answer is restricted to the question and checked against the system&apos;s decision boundary. It can explain what is missing or whether the deadline was met, but it cannot approve, deny, assign liability, or authorise a refund.</p></div>
      <figure className="saidia-diagram"><ZoomableDiagram title="Grounded case question and answer flow"><div className="diagram qa-diagram"><div className="qa-question">Employee question</div><div className="qa-sources"><div><b>Verified case facts</b><span>Dates, complaint, evidence</span></div><div><b>Structured assessment</b><span>Policy match and deadline</span></div><div><b>Semantic retrieval</b><span>Relevant pgvector passages</span></div></div><div className="qa-context">Grounded prompt</div><div className="qa-model">Language model</div><div className="qa-answer"><b>Concise answer</b><span>Within the human-decision boundary</span></div></div></ZoomableDiagram><figcaption>Case facts, calculated results, and retrieved policy passages ground every answer. Click to enlarge.</figcaption></figure>
    </section>

    <section className="case-section saidia-narrative"><p className="case-kicker">TECHNOLOGY CHOICES</p><h2>Why this stack</h2><h3>PostgreSQL, Supabase, and pgvector</h3><p>Claims need relational guarantees because dates, statuses, evidence records, and workflow results must stay consistent. PostgreSQL provides transactions, constraints, indexes, and clear relationships. Supabase supplies managed PostgreSQL and controlled application access. The pgvector extension keeps policy embeddings beside the relational case data, avoiding a separate vector database and another system to operate.</p><h3>all-mpnet-base-v2, retrieval, and the language model</h3><p>Policy passages are divided into smaller chunks and converted into 768-dimensional embeddings with all-mpnet-base-v2. This sentence-transformer is a practical choice for a focused policy library because it offers strong general semantic retrieval and a reproducible indexing process. Semantic search finds relevant passages even when the reviewer’s wording does not exactly match the policy. RAG then combines those passages with verified case facts before the language model writes an explanation or answer.</p><h3>Private S3 evidence storage</h3><p>Original uploads remain private and Make receives time-limited download links only when it needs to attach them to Jira. Images are stored for human inspection. The system does not use computer vision and does not claim to interpret their contents.</p><h3>Make and Jira</h3><p>Make handles the cross-system sequence and attachment transfer. Jira provides an existing operational queue with ownership, status, comments, and evidence. This was more useful than building another custom employee dashboard.</p></section>

    <section className="case-section visual-section reverse"><figure className="saidia-screen wide"><ZoomableImage src="/projects/saidia/make-execution.png" alt="Successful Make automation execution for a Saidia claim"/><figcaption>Successful orchestration, attachment transfer, and response. Click to enlarge.</figcaption></figure><div className="visual-intro"><p className="case-kicker">OPERATIONAL HANDOFF</p><h2>Automation connects the product to real review work</h2><p className="case-copy">After a new claim is created, Make opens the Jira issue, downloads the private evidence, attaches each file, records the Jira key, and returns the result to Streamlit. The data-store record is written only after Jira creation. On a repeat request, the duplicate route can stop before another ticket is created.</p></div></section>

    <section className="case-section saidia-narrative"><p className="case-kicker">REVIEW EXPERIENCE</p><h2>The reviewer receives the facts, policy context, gaps, and original evidence together</h2><p>Make writes the same structured assessment into Jira rather than producing a second, inconsistent summary. The ticket contains the case facts, policy match, deadline result, submitted and missing evidence, and a concise next action. The uploaded files remain available for the employee to inspect, and the human-review notice makes the decision boundary explicit.</p><div className="saidia-gallery two"><figure><ZoomableImage src="/projects/saidia/jira-overview.png" alt="Jira claim ticket with case details and grounded analysis"/><figcaption>Structured case and policy context in Jira. Click to enlarge.</figcaption></figure><figure><ZoomableImage src="/projects/saidia/jira-attachments.png" alt="Jira ticket showing recommendation, human review notice, and attachments"/><figcaption>Actionable recommendation and original attachments. Click to enlarge.</figcaption></figure></div></section>

    <section className="case-section saidia-reliability"><div><p className="case-kicker">PRODUCTION-MINDED RELIABILITY</p><h2>Duplicate protection works across the application, database, and automation</h2><p className="case-copy">A button lock alone cannot protect the system when requests arrive close together or through different processes. Saidia uses one normalized tracking identifier for database and Make lookups. The application checks for an active case early, PostgreSQL enforces one active case per shipment under concurrent requests, and Make checks the same identifier before Jira creation. A repeated report stops the automation and returns the original case reference.</p></div><figure className="saidia-screen"><ZoomableImage src="/projects/saidia/duplicate-reference.png" alt="Saidia duplicate warning returning the existing case reference"/><figcaption>Duplicate stopped before Jira; original reference returned. Click to enlarge.</figcaption></figure></section>

    <section className="case-section saidia-boundaries"><div><p className="case-kicker">WHAT THIS DEMONSTRATES</p><h2>A practical AI system needs boundaries as much as intelligence.</h2></div><div><p>I designed the database model, policy engine, retrieval pipeline, prompts, customer experience, automation handoff, duplicate safeguards, and grounded case Q&amp;A as one coherent workflow.</p><p><b>Current boundaries:</b> NorthStar Parcel and its policies are fictional. The MVP focuses on this single-carrier workflow. Uploaded images are preserved for human review, not analysed by computer vision. The employee workflow uses Jira rather than a custom internal dashboard.</p></div></section>

    <section className="case-closing"><p className="case-kicker">EXPLORE THE PROJECT</p><h2>See the workflow in action or inspect the implementation.</h2><div className="case-actions"><a href={liveApp} target="_blank" rel="noreferrer">Open live application <FiExternalLink/></a><a href={github} target="_blank" rel="noreferrer"><FaGithub/> View source code</a></div></section>
  </main></>;
}
