import type { Metadata } from "next";
import { Footer, Header } from "../../_components";

export const metadata: Metadata = {
  title: "Finance Tracker — Product Case Study | Treva Antony Ogwang",
  description: "How I designed and built a savings-first personal finance prototype connecting budgets, goals, transfers, reminders, forecasts, and reporting.",
  openGraph: { title: "Finance Tracker — Product Case Study", description: "A savings-first personal finance product case study by Treva Antony Ogwang.", images: [] },
  twitter: { card: "summary", title: "Finance Tracker — Product Case Study", description: "A savings-first personal finance product case study by Treva Antony Ogwang.", images: [] },
};

const journeyStages = [
  {stage:"Understand", action:"Review income, spending and available cash", thought:"What can I safely put aside?", emotion:"Uncertain", friction:"Money is visible, but the trade-off is not.", response:"Separate spending, saving transfers and available cash.", signal:"User understands the starting position."},
  {stage:"Plan", action:"Set category budgets and a savings target", thought:"Is this goal realistic for me?", emotion:"Cautious", friction:"A distant target does not explain the monthly commitment.", response:"Calculate the monthly amount and completion date together.", signal:"A viable goal is created."},
  {stage:"Commit", action:"Choose a monthly contribution date and reminder", thought:"How will I remember this every month?", emotion:"Motivated", friction:"Good intentions are easy to postpone.", response:"Create a visible schedule with adjustable reminders.", signal:"A contribution plan is activated."},
  {stage:"Act", action:"Mark a contribution paid, partial or skipped", thought:"Did my money record update correctly?", emotion:"Responsible", friction:"The prototype cannot verify a bank transfer automatically.", response:"Keep manual states explicit, reversible and linked to the ledger.", signal:"A scheduled contribution is resolved."},
  {stage:"Recover", action:"Adjust after overspending or a missed payment", thought:"Can I still reach my goal?", emotion:"Concerned", friction:"Rigid plans can make one missed month feel like failure.", response:"Preserve the skipped item and recalculate future dates.", signal:"The user continues instead of abandoning the goal."},
  {stage:"Learn", action:"Review progress, forecasts and opportunities", thought:"What small change would help next?", emotion:"In control", friction:"Historic reports alone do not guide the next decision.", response:"Translate spending patterns into explainable next actions.", signal:"The next contribution or budget adjustment is made."},
];
const decisions = [
  ["How should saved money appear?", "Model it as a transfer, not an expense", "Available cash falls, while spending reports remain truthful."],
  ["How can an unconnected app verify payment?", "Ask users to mark contributions paid, partial, or skipped", "The MVP is honest about its limitation and keeps each action reversible."],
  ["What happens after a skipped payment?", "Keep the missed item and extend the schedule", "History is preserved and the plan remains achievable."],
  ["Where should recommendations live?", "One savings-level opportunity hub", "Insights remain discoverable without being repeated inside every goal."],
];

function Screen({ src, alt, label, title, text }: { src: string; alt: string; label: string; title: string; text: string }) {
  return <figure className="product-screen"><div className="phone-frame"><img src={src} alt={alt}/></div><figcaption><span>{label}</span><h3>{title}</h3><p>{text}</p></figcaption></figure>;
}

export default function FinanceTrackerCaseStudy() {
  return <><Header active="Projects"/><main className="case-container">
    <section className="case-hero"><p className="case-kicker">INDEPENDENT PRODUCT CASE STUDY · 2026</p><h1>Finance Tracker: turning monthly intentions into savings progress</h1><p className="case-deck">I shaped and built a working mobile prototype around a deceptively difficult question: how can people plan spending, move money into savings, and still trust the balance they see?</p><div className="case-facts"><span><b>My role</b>Product Owner & Prototype Developer</span><span><b>Scope</b>Product framing to working prototype</span><span><b>Built with</b>React Native, TypeScript & Supabase</span><span><b>Status</b>Prototype ready for user validation</span></div></section>

    <section className="case-summary"><div><p className="case-kicker">THE PRODUCT OPPORTUNITY</p><h2>A transaction log explains the past. A useful finance product should also help shape the next decision.</h2></div><div><p>Qualitative research among my peers surfaced a recurring gap: people could see where their money had gone, but struggled to connect monthly spending decisions with specific savings goals and future progress. That insight became the starting point for Finance Tracker.</p><p className="case-note">I translated the themes from those conversations into a product hypothesis: one connected experience should help users see what is available, reserve money for goals, follow a contribution plan, and understand how today&apos;s spending changes tomorrow&apos;s outcome.</p></div></section>

    <section className="case-section"><p className="case-kicker">DISCOVERY</p><h2>Peer research shaped the problem I chose to solve</h2><div className="research-grid"><article><span>OBSERVED NEED</span><b>Visibility was not enough</b><p>Participants could review transactions, but still found it difficult to translate that information into a realistic saving routine.</p></article><article><span>BEHAVIOURAL FRICTION</span><b>Goals felt disconnected from everyday spending</b><p>Saving intentions and spending decisions were managed separately, making trade-offs harder to understand.</p></article><article><span>PRODUCT RESPONSE</span><b>Connect planning, action, and feedback</b><p>The concept links budgets, scheduled contributions, reminders, transaction history, forecasts, and progress in one loop.</p></article></div></section>

    <section className="case-section persona-section"><div><p className="case-kicker">PRIMARY PERSONA</p><h2>Meet Maya, an early-career monthly saver</h2><p className="case-copy">Maya is a representative persona synthesised from themes in my peer research. She has a regular monthly income and more than one financial goal, but manages spending and saving in separate places.</p></div><div className="persona-card"><div className="persona-head"><span>REPRESENTATIVE USER</span><b>Maya · 27 · Berlin</b><p>Early-career professional paid monthly</p></div><div className="persona-details"><article><span>GOAL</span><p>Build an emergency buffer while saving for a holiday.</p></article><article><span>BEHAVIOUR</span><p>Checks transactions often, but decides what to save informally.</p></article><article><span>FRUSTRATION</span><p>A budget can look healthy even when planned savings have not moved.</p></article><article><span>NEED</span><p>A realistic plan, a timely prompt, and confidence that every figure agrees.</p></article></div><blockquote>“Help me know what I can spend now without losing sight of what I am saving for.”</blockquote><small>Persona statement synthesised from research themes; not presented as a verbatim participant quote.</small></div></section>

    <section className="case-section"><p className="case-kicker">PROBLEM FRAMING</p><h2>The system had to answer four questions consistently</h2><div className="principle-grid"><article><b>What is still spendable?</b><p>Income minus expenses is incomplete when money has already been transferred to savings or investments.</p></article><article><b>Is a transfer an expense?</b><p>No. It changes where money is held, but should not inflate consumption or distort category reporting.</p></article><article><b>What if the plan is missed?</b><p>A skipped contribution should remain visible, while the future schedule adapts rather than rewriting history.</p></article><article><b>Can a forecast be trusted?</b><p>The first model should be transparent enough for a user to understand and challenge.</p></article></div></section>

    <section className="case-section"><p className="case-kicker">USER JOURNEY MAP</p><h2>From uncertainty to a repeatable saving habit</h2><p className="case-copy journey-intro">Scenario: Maya has been paid and wants to fund two goals without overstating what remains available for the month.</p><div className="journey-map"><div className="journey-row journey-stages"><b>Stage</b>{journeyStages.map((item,index)=><article key={item.stage}><span>{String(index+1).padStart(2,"0")}</span><strong>{item.stage}</strong></article>)}</div><div className="journey-row"><b>Action</b>{journeyStages.map(item=><p key={item.stage}>{item.action}</p>)}</div><div className="journey-row"><b>Thought</b>{journeyStages.map(item=><p key={item.stage}>“{item.thought}”</p>)}</div><div className="journey-row journey-emotions"><b>Emotion</b>{journeyStages.map(item=><p key={item.stage}>{item.emotion}</p>)}</div><div className="journey-row journey-friction"><b>Pain point</b>{journeyStages.map(item=><p key={item.stage}>{item.friction}</p>)}</div><div className="journey-row journey-response"><b>Product response</b>{journeyStages.map(item=><p key={item.stage}>{item.response}</p>)}</div><div className="journey-row"><b>Success signal</b>{journeyStages.map(item=><p key={item.stage}>{item.signal}</p>)}</div></div><p className="journey-caption">This is the current-state journey translated into a future-state product experience. It keeps user behaviour, friction, product choices, and measurement in the same view.</p></section>

    <section className="case-section"><p className="case-kicker">PRODUCT SYSTEM</p><h2>One financial event, several coordinated updates</h2><p className="case-copy system-explainer">This diagram sits underneath the user journey because it describes what the product must coordinate behind every user action.</p><div className="system-map"><div className="system-source"><span>INPUTS</span><b>Income · expenses · goal plans · contribution status</b></div><div className="system-arrow">↓</div><div className="system-core"><span>SHARED FINANCIAL MODEL</span><b>Transactions and transfers become the source of truth</b></div><div className="system-arrow">↓</div><div className="system-outputs"><article><span>NOW</span><b>Available cash</b></article><article><span>PLAN</span><b>Budget position</b></article><article><span>PROGRESS</span><b>Goal balance & schedule</b></article><article><span>LEARN</span><b>Reports & opportunities</b></article></div></div></section>

    <section className="case-section visual-section"><div className="visual-intro"><p className="case-kicker">01 · GOAL PORTFOLIO</p><h2>Make progress visible before asking for another action</h2><p className="case-copy">The Savings area begins with total progress across goals, surfaces savings opportunities near the top, and gives each goal a clear amount, percentage, estimated completion date, and monthly target.</p></div><Screen src="/projects/finance-tracker/savings-overview.png" alt="Finance Tracker savings overview with two active goals" label="SAVINGS OVERVIEW" title="A portfolio of active goals" text="The overview makes the trade-off between goal size, current progress, and monthly commitment visible at a glance."/></section>

    <section className="case-section visual-section reverse"><Screen src="/projects/finance-tracker/create-goal.png" alt="New savings goal form with calculated completion date" label="PLAN BUILDER" title="Two inputs, one adjustable plan" text="Changing the contribution recalculates completion; changing the desired date recalculates the monthly amount."/><div className="visual-intro"><p className="case-kicker">02 · PLAN CREATION</p><h2>Let the user negotiate with the plan before committing</h2><p className="case-copy">A goal name and target are not enough. The plan builder combines the amount already saved, monthly contribution, transfer day, and estimated completion date. The date is an output, but it is also adjustable—turning the forecast into a practical planning control.</p><div className="mini-rule"><b>Remaining amount</b><span>Target − already saved</span><b>Months required</b><span>Remaining ÷ monthly contribution</span><b>Completion</b><span>Current date + required contribution cycles</span></div></div></section>

    <section className="case-section visual-section"><div className="visual-intro"><p className="case-kicker">03 · GOAL MOMENTUM</p><h2>Pair progress with a concrete next step</h2><p className="case-copy">The goal summary answers where the user stands; the payment schedule answers what happens next. Contribution timing and reminders turn a distant target into a repeatable monthly action.</p></div><Screen src="/projects/finance-tracker/payment-schedule.png" alt="Payment schedule with contribution reminder and upcoming dates" label="PAYMENT SCHEDULE" title="Turn intention into a routine" text="The schedule keeps the next contribution prominent and lets the user configure a reminder before each planned transfer."/></section>

    <section className="case-section"><p className="case-kicker">DECISIONS & TRADE-OFFS</p><h2>The product rules behind the interface</h2><div className="decision-table"><div className="decision-head"><b>Product question</b><b>Decision</b><b>Reason</b></div>{decisions.map(row=><div className="decision-row" key={row[0]}>{row.map(cell=><p key={cell}>{cell}</p>)}</div>)}</div></section>

    <section className="case-section split-section"><div><p className="case-kicker">CONTRIBUTION STATES</p><h2>Every manual action remains traceable and reversible</h2><p className="case-copy">Without a live bank connection, automatic confirmation would create false certainty. The MVP therefore asks the user to update each scheduled item. Marking it paid creates a linked transfer and updates the goal; changing it later reverses the linked record. A partial payment records the actual amount. A skipped payment remains in history and extends the plan.</p></div><div className="state-flow"><div className="state-main">Upcoming contribution</div><div className="state-options"><span className="paid">Paid</span><span className="partial">Partial</span><span className="skipped">Skipped</span></div><div className="state-result">Recalculate goal · available cash · transaction history · future schedule</div></div></section>

    <section className="case-section visual-section"><div className="visual-intro"><p className="case-kicker">04 · FINANCIAL INTEGRITY</p><h2>Connect the savings plan to the rest of the money model</h2><p className="case-copy">Savings should be budgeted for, but not counted as ordinary spending. The budget view therefore exposes a separate Save &amp; Invest plan, calculated from active goals. Confirmed contributions appear in the transaction ledger as transfers and reduce available cash.</p></div><Screen src="/projects/finance-tracker/budget-link.png" alt="Budget screen with Save and Invest plan linked to savings goals" label="BUDGET CONNECTION" title="Reserve money without mislabelling it" text="Planned contributions sit alongside spending budgets, preserving the distinction between consumption and wealth-building."/></section>

    <section className="case-section"><p className="case-kicker">05 · SINGLE SOURCE OF TRUTH</p><h2>A contribution should leave an auditable footprint</h2><div className="screen-pair"><Screen src="/projects/finance-tracker/transactions.png" alt="Transaction history with expenses and an investment contribution" label="TRANSACTION LEDGER" title="One history for expenses and transfers" text="Calendar markers and categories make ordinary spending and saving or investment transfers distinguishable without splitting the financial record."/><Screen src="/projects/finance-tracker/add-transaction.png" alt="Add transaction form for recording an expense" label="MANUAL CAPTURE" title="Capture the data needed for decisions" text="Until bank connectivity is introduced, users can record income and expenses with category, date, time, and context."/></div></section>

    <section className="case-section visual-section reverse"><Screen src="/projects/finance-tracker/recently-deleted.png" alt="Recently Deleted screen with restore and permanent-delete actions" label="RECOVERY & CONTROL" title="Deletion is reversible for 30 days" text="A recovery window protects users from accidental deletion while still providing an explicit permanent-delete action."/><div className="visual-intro"><p className="case-kicker">DATA LIFECYCLE</p><h2>Financial records need a recovery path</h2><p className="case-copy">Deleting a transaction can change balances, budgets, forecasts, and historical reports. Recently Deleted preserves the record for 30 days, shows when it was removed, and lets the user restore it or deliberately erase it permanently.</p></div></section>

    <section className="case-section"><p className="case-kicker">06 · LEARNING OVER TIME</p><h2>Use reporting for reflection, not dashboard decoration</h2><div className="principle-grid"><article><b>Current month</b><p>The Home view answers what came in, what was spent, what moved to goals, and what remains available.</p></article><article><b>Historical view</b><p>Reports compare income, expenses, Save &amp; Invest transfers, budget performance, and savings rate over time.</p></article></div></section>

    <section className="case-section"><p className="case-kicker">MVP PRIORITISATION</p><h2>Build the smallest trustworthy loop first</h2><div className="priority-grid"><article><span>MUST</span><b>Make the plan usable</b><p>Goals, schedules, reminders, contribution states, linked transfers, and accurate available cash.</p></article><article><span>SHOULD</span><b>Help users adjust</b><p>Spending projections, savings opportunities, reversals, partial payments, and reporting.</p></article><article><span>COULD</span><b>Deepen motivation</b><p>Milestones, alternative goal scenarios, shared goals, and recommendation experiments.</p></article><article><span>LATER</span><b>Automate responsibly</b><p>Open banking, transfer verification, automated deposits, and investment-plan execution.</p></article></div></section>

    <section className="case-section"><p className="case-kicker">MEASUREMENT PLAN</p><h2>Measure funded plans—not goals created</h2><p className="case-copy metric-intro">The product should be judged by whether users follow through on realistic plans. Creating more goals is not success if scheduled contributions remain unpaid.</p><div className="metric-tree"><div className="north-star"><span>NORTH STAR METRIC</span><b>Monthly planned-contribution completion rate</b><p><strong>Confirmed contribution value ÷ contribution value scheduled to be due that month</strong></p><p>Measured across active goals with at least one payment due. Partial payments count by value; skipped and overdue payments remain in the denominator. This connects product use directly to real savings progress.</p></div><div className="metric-branches"><article><span>ACTIVATION</span><b>Funded-plan activation</b><p>New users who create a goal with an amount, contribution schedule, and first payment due within 30 days.</p></article><article><span>FOLLOW-THROUGH</span><b>On-time resolution rate</b><p>Payments marked paid, partial, or skipped within three days of their scheduled date. This measures active plan management, not only perfect behaviour.</p></article><article><span>VALUE</span><b>Median monthly savings rate</b><p>Confirmed Save &amp; Invest transfers divided by recorded income, reported at the median to reduce distortion from outliers.</p></article><article><span>RETENTION</span><b>Third-cycle continuation</b><p>Users who still have an active goal and resolve its third scheduled contribution.</p></article></div><div className="metric-guardrails"><span><b>Forecast accuracy</b>Difference between predicted and actual month-end spending</span><span><b>Reminder health</b>Notification opt-out rate after a reminder</span><span><b>Data integrity</b>Linked-transfer or balance reconciliation failures</span><span><b>Trust</b>Contribution reversals caused by an incorrect status</span></div></div></section>

    <section className="case-section"><p className="case-kicker">VALIDATION PLAN</p><h2>What I would test next</h2><div className="principle-grid"><article><b>Comprehension test</b><p>Can users explain why a savings transfer reduces available cash but does not increase expenses?</p></article><article><b>Plan-building usability</b><p>Can users predict what will happen when they change the target date or monthly amount?</p></article><article><b>Reminder experiment</b><p>Compare reminder timing and contribution completion without creating notification fatigue.</p></article><article><b>Forecast trust</b><p>Test whether confidence labels and plain-language assumptions improve understanding of projections.</p></article></div></section>

    <section className="case-section"><p className="case-kicker">FUTURE ROADMAP</p><h2>Move from manual tracking to connected money management</h2><p className="case-copy roadmap-intro">The next phase would use regulated open-banking providers—such as Tink, TrueLayer, or Plaid—to connect consented bank accounts and synchronise transactions. Provider selection would depend on European coverage, data quality, consent flows, cost, security, and regulatory requirements.</p><div className="roadmap"><article><span>NOW · PROTOTYPE</span><b>Prove the core model</b><p>Manual records, individual budgets, savings goals, reminders, reversible contributions, reporting, and deleted-transaction recovery.</p></article><article><span>NEXT · CONNECT</span><b>Open banking and account aggregation</b><p>Connect multiple bank accounts, import transactions, reconcile duplicates, categorise activity, and refresh balances with clear consent controls.</p></article><article><span>THEN · COLLABORATE</span><b>Shared financial spaces</b><p>Household budgets for partners, shared saving targets, permissions, contribution ownership, and transparent activity histories.</p></article><article><span>LATER · PLAN TOGETHER</span><b>Trip and group budgets</b><p>Create a shared pool, track individual contributions, set a trip spending limit, record group expenses, and settle balances fairly.</p></article></div><div className="roadmap-guardrails"><b>Non-negotiable guardrails</b><span>Explicit consent</span><span>Read-only access by default</span><span>Clear ownership and permissions</span><span>Duplicate detection</span><span>Audit history</span><span>Easy disconnection and data deletion</span></div></section>

    <section className="case-closing"><p className="case-kicker">REFLECTION</p><h2>The interface was not the hardest part. The accounting rules were.</h2><p>A convincing finance product cannot let each screen calculate its own version of reality. The central product work was defining how income, expenses, budgets, transfers, goals, skipped payments, reversals, and forecasts affect one another—then making those rules visible enough for a user to trust.</p></section>
  </main><Footer/></>;
}
