import { Header } from "../../_header";

const metrics = [
  ["25,585", "catalogue products"],
  ["88,124", "final test users"],
  ["5.64%", "test Hit Rate@10"],
  ["97.05%", "catalogue coverage"],
];

const modelRows = [
  ["Popularity baseline", "Validation", "3.07%", "1.10%", "1.55%", "0.07%"],
  ["Collaborative + fallback", "Validation", "5.30%", "2.37%", "3.05%", "97.57%"],
  ["Hybrid 70/30", "Validation", "5.95%", "2.66%", "3.43%", "97.26%"],
  ["Hybrid 70/30", "Final test", "5.64%", "2.50%", "3.23%", "97.05%"],
];

function ProjectImage({ src, alt, caption }: { src: string; alt: string; caption: string }) {
  return <figure className="game-rec-screen"><img src={src} alt={alt}/><figcaption>{caption}</figcaption></figure>;
}

export default function SaidiaGameRecommender() {
  return <><Header active="Projects"/><main className="case-container game-rec-case">
    <section className="case-hero">
      <p className="case-kicker">MACHINE LEARNING · RECOMMENDER SYSTEMS · PRODUCT UI · 2026</p>
      <h1>From 814,586 interactions to an explainable product-discovery experience</h1>
      <p className="case-deck">Saidia is a hybrid game recommender built from Amazon review and product data. It combines item relationships learned from positive ratings with text similarity from product metadata, then serves the saved results through a Streamlit shopping interface.</p>
      <div className="case-facts"><span><b>Role</b>Data science · ML engineering · product UI</span><span><b>Stack</b>Python · SciPy · scikit-learn · Streamlit</span><span><b>Data</b>Amazon Reviews 2023 · Video Games</span><span><b>Status</b>Deployed and publicly accessible</span></div>
      <div className="case-actions"><a href="https://saidia-game-recommender.streamlit.app/" target="_blank" rel="noreferrer">Try the live recommender ↗</a><a href="https://github.com/Begge10850/saidia-recommender" target="_blank" rel="noreferrer">View repository ↗</a></div>
    </section>

    <section className="case-summary"><div><p className="case-kicker">THE PRODUCT AT A GLANCE</p><h2>A recommendation model is more useful when people can see why different products appear.</h2></div><div><p>I built the project as both a ranking experiment and a product interface. The model work compares different sources of recommendation evidence. The application turns those results into clear ways to browse and explore the catalogue.</p><p className="case-note">Visitors can open a product, compare behavioural and content neighbours, build a temporary likes profile, and receive ten recommendations. The interface labels each type of result so that similar products are not confused with products liked by overlapping users.</p></div></section>

    <section className="case-section game-rec-intro"><p className="case-kicker">PRODUCT EXPERIENCE</p><h2>The interface separates three questions that are easy to mix up</h2><div className="game-rec-three"><article><span>01</span><b>What did similar users like?</b><p>Users also liked is based on positive-rating overlap between products. It describes a behavioural association, not a verified joint purchase.</p></article><article><span>02</span><b>Which products look similar?</b><p>Similar products compares words in titles, categories, descriptions, and feature fields. It can surface relevant items even when behavioural history is limited.</p></article><article><span>03</span><b>What fits this profile?</b><p>Recommended for you combines evidence from every item in the visitor&apos;s temporary likes profile, removes items already selected, and returns the ten highest-ranked candidates.</p></article></div></section>

    <section className="case-section game-rec-gallery"><ProjectImage src="/projects/saidia-game-recommender/catalogue.png" alt="Saidia catalogue with game and accessory cards" caption="Browse the 25,585-product catalogue, inspect related products, or add an item directly to My likes."/><ProjectImage src="/projects/saidia-game-recommender/users-also-liked.png" alt="Selected product with Users also liked recommendations" caption="A selected product opens into behavioural neighbours while preserving the current likes profile."/><ProjectImage src="/projects/saidia-game-recommender/similar-products-and-likes.png" alt="Similar product recommendations and the visitor likes profile" caption="Content neighbours and removable likes create an exploratory loop rather than a one-shot result page."/></section>

    <section className="case-section"><p className="case-kicker">DATA AND TARGET DEFINITION</p><h2>The first modelling choice was deciding what counted as positive evidence</h2><p className="game-rec-lead">The source contains explicit star ratings, not clicks or purchases. I converted ratings of four and five into a binary positive signal for top ten ranking. Ratings from one to three were retained during preparation but were not used as confirmed dislikes. A missing rating was also treated as unknown. This matters because absence of feedback does not show that a user saw and rejected a product.</p><div className="game-rec-metrics">{metrics.map(([value,label])=><article key={label}><strong>{value}</strong><span>{label}</span></article>)}</div><p className="game-rec-method-note">This design asks a narrow question: given products a user rated positively in the past, can the system recover a later positively rated product? It does not estimate purchase probability or predict the original star rating.</p></section>

    <section className="case-section game-rec-split"><div><p className="case-kicker">EVALUATION DESIGN</p><h2>Each user was evaluated on a product rated later than their training history</h2><p>Eligible users needed at least three distinct positive-rating times. For each user, earlier positive ratings formed the development history, the second-newest positive rating became the validation target, and the newest became the final test target. After model selection, the validation interaction returned to the final training history.</p><p>This is a user-level chronological leave-last-out design. It prevents a user&apos;s own held-out targets from appearing in that user&apos;s training history. It does not enforce one global time cutoff across all users, so it should not be described as a complete simulation of production deployment.</p></div><div className="game-rec-checks"><article><b>0</b><span>cases where a user&apos;s training time reached or passed the validation target</span></article><article><b>0</b><span>cases where a user&apos;s final training time reached or passed the test target</span></article><article><b>13</b><span>users excluded because tied timestamps made target order ambiguous</span></article><article><b>100%</b><span>positive rows reconciled across training and held-out tables</span></article></div></section>

    <section className="case-section"><p className="case-kicker">MODEL SYSTEM</p><h2>The hybrid combines evidence that fails in different ways</h2><div className="game-rec-models"><article><span>BEHAVIOUR</span><b>Collaborative item similarity</b><p>A sparse user by product matrix records positive ratings. Cosine similarity then identifies products with comparable user patterns. This signal is useful when products have enough shared history, but weak for sparse or new items.</p></article><article><span>METADATA</span><b>TF-IDF content similarity</b><p>TF-IDF gives more weight to terms that distinguish one product from the wider catalogue. Cosine similarity compares the resulting product vectors. This supports sparse items, although it can overvalue shared wording without understanding meaning.</p></article><article><span>FALLBACK</span><b>Popularity ranking</b><p>Popularity provides a non-personalised benchmark and fills empty positions when the two neighbour sources produce fewer than ten eligible candidates. It is useful for availability, but poor for catalogue breadth.</p></article></div><div className="game-rec-pipeline"><span>Products in My likes</span><i>→</i><span>Collaborative and content candidates</span><i>→</i><strong>Normalise, then combine 70% behaviour and 30% content</strong><i>→</i><span>Remove selected products</span><i>→</i><span>Top 10</span></div><p className="game-rec-method-note">The 70/30 weighting was not chosen from intuition. Four candidate weights were compared on validation NDCG@10. The final test data was used only after the weighting was fixed.</p></section>

    <section className="case-section"><p className="case-kicker">OFFLINE EVALUATION</p><h2>The hybrid found more held-out products and ranked successful matches higher</h2><p className="game-rec-lead">Hit Rate@10 records whether the held-out product appears anywhere in the ten results. MRR@10 gives more credit when the first correct result appears near rank one. NDCG@10 also discounts lower positions and is the selection metric used here. Catalogue coverage reports the share of eligible products that appeared at least once across all recommendation lists. It measures system-wide breadth, not diversity within one user&apos;s list.</p><div className="game-rec-table"><table><thead><tr><th>Model</th><th>Split</th><th>Hit Rate@10</th><th>MRR@10</th><th>NDCG@10</th><th>Coverage</th></tr></thead><tbody>{modelRows.map((row)=><tr key={`${row[0]}-${row[1]}`}>{row.map((cell)=><td key={cell}>{cell}</td>)}</tr>)}</tbody></table></div><p className="game-rec-evidence">On validation data, the hybrid reached 5.95% Hit Rate@10 compared with 5.30% for collaborative recommendations and 3.07% for popularity. On the untouched final targets, it reached 5.64%, which is about one recovered product for every eighteen evaluated users. The hybrid also retained 97.05% catalogue coverage on the final test. These are offline ranking results. They do not measure satisfaction, conversion, revenue, or causal business impact.</p></section>

    <section className="case-section game-rec-evidence-shot"><div><p className="case-kicker">EVIDENCE IN THE PRODUCT</p><h2>The evaluation page tells visitors what was measured</h2><p>The deployed application includes the model comparison, selected weight, metric definitions, and known limitations. It also states that these figures come from historical offline evaluation. They do not change when a visitor selects products, and they should not be read as live performance data.</p></div><ProjectImage src="/projects/saidia-game-recommender/model-evidence-overview.png" alt="Saidia offline evaluation evidence page" caption="The evidence page separates historical test results from recommendations generated during the current session."/></section>

    <section className="case-section game-rec-references"><p className="case-kicker">RESEARCH BASIS</p><h2>The design follows established recommender-system ideas, with its own scope clearly stated</h2><div><a href="https://arxiv.org/abs/2403.03952" target="_blank" rel="noreferrer"><b>Hou et al., Amazon Reviews 2023</b><span>Documents the source dataset and its combination of large-scale review interactions with rich item metadata.</span></a><a href="https://yifanhu.net/PUB/cf.pdf" target="_blank" rel="noreferrer"><b>Hu, Koren and Volinsky, 2008</b><span>Provides the key caution that positive observations and missing feedback carry different meanings in positive-only recommendation settings.</span></a><a href="https://arxiv.org/abs/2010.11060" target="_blank" rel="noreferrer"><b>Ji et al., temporal leakage in offline evaluation</b><span>Motivates the explicit distinction between user-level chronology and a stricter global temporal split.</span></a><a href="https://doi.org/10.1145/582415.582418" target="_blank" rel="noreferrer"><b>Järvelin and Kekäläinen, 2002</b><span>Introduces cumulative-gain ranking measures that give more value to relevant results near the top of a ranked list.</span></a><a href="https://scikit-learn.org/stable/modules/metrics.html" target="_blank" rel="noreferrer"><b>scikit-learn pairwise metrics documentation</b><span>Documents cosine similarity and its relationship to normalised TF-IDF vectors used by the content model.</span></a></div></section>

    <section className="case-section game-rec-limits"><div><p className="case-kicker">LIMITATIONS</p><h2>What this evaluation does not answer</h2></div><ul><li>Review ratings are expressions of preference, not verified purchases or shopping baskets.</li><li>Ratings below four and products with no rating are not modelled as explicit negative preferences.</li><li>Product metadata is treated as one catalogue snapshot rather than reconstructed at every historical interaction time.</li><li>The leave-last-out split preserves order within each user, but it does not impose one global training cutoff.</li><li>One held-out positive item per user gives a clear test but does not measure whether the rest of the list is useful, novel, or diverse.</li><li>The application uses temporary session profiles, with no authentication or persistent feedback loop.</li><li>No online experiment measured user satisfaction, conversion, retention, or revenue.</li></ul></section>

    <section className="case-closing"><p className="case-kicker">REFLECTION</p><h2>The main lesson was that evaluation design deserves as much attention as model design.</h2><p>Building item similarity was only one part of the work. The project also required a precise target, a baseline, separate validation and test stages, checks on time order, metrics for both ranking and catalogue reach, and language that does not overstate what review data can prove. The deployed interface now makes those choices visible instead of hiding them behind a recommendation score.</p><div className="case-actions"><a href="https://saidia-game-recommender.streamlit.app/" target="_blank" rel="noreferrer">Open live application ↗</a><a href="https://github.com/Begge10850/saidia-recommender" target="_blank" rel="noreferrer">Inspect the technical repository ↗</a></div></section>
  </main></>;
}
